version: '3'

services:
    php8:
        build:
            context: ./docker/php8
        hostname: php8
        ports:
            - "9001:9000"
        volumes:
            - ./projects/:/var/www/html/
            - ./docker/php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php8/php.ini:/usr/local/etc/php/php.ini
    nginx:
        platform: linux/x86_64
        image: nginx:1.13.8
        ports:
            - "80:80"
        volumes:
            - ./projects/:/var/www/html/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php8
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        ports:
            - "3306:3306"
        depends_on:
            - php8
        volumes:
            - mysqlData:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "8080:80"

volumes:
    mysqlData:
        driver: local