<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
	{

		public function run()
			{
				\DB::table('cities')->delete();
				\DB::table('cities')->insert(array(
					0  => array(
						'country_id' => 212,
						'id'         => 1,
						'name'       => 'ADANA',
						'plate_no'   => '1',
						'phone_code' => '322',
					),
					1  => array(
						'country_id' => 212,
						'id'         => 2,
						'name'       => 'ADIYAMAN',
						'plate_no'   => '2',
						'phone_code' => '416',
					),
					2  => array(
						'country_id' => 212,
						'id'         => 3,
						'name'       => 'AFYONKARAHİSAR',
						'plate_no'   => '3',
						'phone_code' => '272',
					),
					3  => array(
						'country_id' => 212,
						'id'         => 4,
						'name'       => 'AĞRI',
						'plate_no'   => '4',
						'phone_code' => '472',
					),
					4  => array(
						'country_id' => 212,
						'id'         => 5,
						'name'       => 'AKSARAY',
						'plate_no'   => '68',
						'phone_code' => '382',
					),
					5  => array(
						'country_id' => 212,
						'id'         => 6,
						'name'       => 'AMASYA',
						'plate_no'   => '5',
						'phone_code' => '358',
					),
					6  => array(
						'country_id' => 212,
						'id'         => 7,
						'name'       => 'ANKARA',
						'plate_no'   => '6',
						'phone_code' => '312',
					),
					7  => array(
						'country_id' => 212,
						'id'         => 8,
						'name'       => 'ANTALYA',
						'plate_no'   => '7',
						'phone_code' => '242',
					),
					8  => array(
						'country_id' => 212,
						'id'         => 9,
						'name'       => 'ARDAHAN',
						'plate_no'   => '75',
						'phone_code' => '478',
					),
					9  => array(
						'country_id' => 212,
						'id'         => 10,
						'name'       => 'ARTVİN',
						'plate_no'   => '8',
						'phone_code' => '466',
					),
					10 => array(
						'country_id' => 212,
						'id'         => 11,
						'name'       => 'AYDIN',
						'plate_no'   => '9',
						'phone_code' => '256',
					),
					11 => array(
						'country_id' => 212,
						'id'         => 12,
						'name'       => 'BALIKESİR',
						'plate_no'   => '10',
						'phone_code' => '266',
					),
					12 => array(
						'country_id' => 212,
						'id'         => 13,
						'name'       => 'BARTIN',
						'plate_no'   => '74',
						'phone_code' => '378',
					),
					13 => array(
						'country_id' => 212,
						'id'         => 14,
						'name'       => 'BATMAN',
						'plate_no'   => '72',
						'phone_code' => '488',
					),
					14 => array(
						'country_id' => 212,
						'id'         => 15,
						'name'       => 'BAYBURT',
						'plate_no'   => '69',
						'phone_code' => '458',
					),
					15 => array(
						'country_id' => 212,
						'id'         => 16,
						'name'       => 'BİLECİK',
						'plate_no'   => '11',
						'phone_code' => '228',
					),
					16 => array(
						'country_id' => 212,
						'id'         => 17,
						'name'       => 'BİNGÖL',
						'plate_no'   => '12',
						'phone_code' => '426',
					),
					17 => array(
						'country_id' => 212,
						'id'         => 18,
						'name'       => 'BİTLİS',
						'plate_no'   => '13',
						'phone_code' => '434',
					),
					18 => array(
						'country_id' => 212,
						'id'         => 19,
						'name'       => 'BOLU',
						'plate_no'   => '14',
						'phone_code' => '374',
					),
					19 => array(
						'country_id' => 212,
						'id'         => 20,
						'name'       => 'BURDUR',
						'plate_no'   => '15',
						'phone_code' => '248',
					),
					20 => array(
						'country_id' => 212,
						'id'         => 21,
						'name'       => 'BURSA',
						'plate_no'   => '16',
						'phone_code' => '224',
					),
					21 => array(
						'country_id' => 212,
						'id'         => 22,
						'name'       => 'ÇANAKKALE',
						'plate_no'   => '17',
						'phone_code' => '286',
					),
					22 => array(
						'country_id' => 212,
						'id'         => 23,
						'name'       => 'ÇANKIRI',
						'plate_no'   => '18',
						'phone_code' => '376',
					),
					23 => array(
						'country_id' => 212,
						'id'         => 24,
						'name'       => 'ÇORUM',
						'plate_no'   => '19',
						'phone_code' => '364',
					),
					24 => array(
						'country_id' => 212,
						'id'         => 25,
						'name'       => 'DENİZLİ',
						'plate_no'   => '20',
						'phone_code' => '258',
					),
					25 => array(
						'country_id' => 212,
						'id'         => 26,
						'name'       => 'DİYARBAKIR',
						'plate_no'   => '21',
						'phone_code' => '412',
					),
					26 => array(
						'country_id' => 212,
						'id'         => 27,
						'name'       => 'DÜZCE',
						'plate_no'   => '81',
						'phone_code' => '380',
					),
					27 => array(
						'country_id' => 212,
						'id'         => 28,
						'name'       => 'EDİRNE',
						'plate_no'   => '22',
						'phone_code' => '284',
					),
					28 => array(
						'country_id' => 212,
						'id'         => 29,
						'name'       => 'ELAZIĞ',
						'plate_no'   => '23',
						'phone_code' => '424',
					),
					29 => array(
						'country_id' => 212,
						'id'         => 30,
						'name'       => 'ERZİNCAN',
						'plate_no'   => '24',
						'phone_code' => '446',
					),
					30 => array(
						'country_id' => 212,
						'id'         => 31,
						'name'       => 'ERZURUM',
						'plate_no'   => '25',
						'phone_code' => '442',
					),
					31 => array(
						'country_id' => 212,
						'id'         => 32,
						'name'       => 'ESKİŞEHİR',
						'plate_no'   => '26',
						'phone_code' => '222',
					),
					32 => array(
						'country_id' => 212,
						'id'         => 33,
						'name'       => 'GAZİANTEP',
						'plate_no'   => '27',
						'phone_code' => '342',
					),
					33 => array(
						'country_id' => 212,
						'id'         => 34,
						'name'       => 'GİRESUN',
						'plate_no'   => '28',
						'phone_code' => '454',
					),
					34 => array(
						'country_id' => 212,
						'id'         => 35,
						'name'       => 'GÜMÜŞHANE',
						'plate_no'   => '29',
						'phone_code' => '456',
					),
					35 => array(
						'country_id' => 212,
						'id'         => 36,
						'name'       => 'HAKKARİ',
						'plate_no'   => '30',
						'phone_code' => '438',
					),
					36 => array(
						'country_id' => 212,
						'id'         => 37,
						'name'       => 'HATAY',
						'plate_no'   => '31',
						'phone_code' => '326',
					),
					37 => array(
						'country_id' => 212,
						'id'         => 38,
						'name'       => 'IĞDIR',
						'plate_no'   => '76',
						'phone_code' => '476',
					),
					38 => array(
						'country_id' => 212,
						'id'         => 39,
						'name'       => 'ISPARTA',
						'plate_no'   => '32',
						'phone_code' => '246',
					),
					39 => array(
						'country_id' => 212,
						'id'         => 40,
						'name'       => 'İSTANBUL',
						'plate_no'   => '34',
						'phone_code' => '212-216',
					),
					40 => array(
						'country_id' => 212,
						'id'         => 41,
						'name'       => 'İZMİR',
						'plate_no'   => '35',
						'phone_code' => '232',
					),
					41 => array(
						'country_id' => 212,
						'id'         => 42,
						'name'       => 'KAHRAMANMARAŞ',
						'plate_no'   => '46',
						'phone_code' => '344',
					),
					42 => array(
						'country_id' => 212,
						'id'         => 43,
						'name'       => 'KARABÜK',
						'plate_no'   => '78',
						'phone_code' => '370',
					),
					43 => array(
						'country_id' => 212,
						'id'         => 44,
						'name'       => 'KARAMAN',
						'plate_no'   => '70',
						'phone_code' => '338',
					),
					44 => array(
						'country_id' => 212,
						'id'         => 45,
						'name'       => 'KARS',
						'plate_no'   => '36',
						'phone_code' => '474',
					),
					45 => array(
						'country_id' => 212,
						'id'         => 46,
						'name'       => 'KASTAMONU',
						'plate_no'   => '37',
						'phone_code' => '366',
					),
					46 => array(
						'country_id' => 212,
						'id'         => 47,
						'name'       => 'KAYSERİ',
						'plate_no'   => '38',
						'phone_code' => '352',
					),
					47 => array(
						'country_id' => 212,
						'id'         => 48,
						'name'       => 'KIRIKKALE',
						'plate_no'   => '71',
						'phone_code' => '318',
					),
					48 => array(
						'country_id' => 212,
						'id'         => 49,
						'name'       => 'KIRKLARELİ',
						'plate_no'   => '39',
						'phone_code' => '288',
					),
					49 => array(
						'country_id' => 212,
						'id'         => 50,
						'name'       => 'KIRŞEHİR',
						'plate_no'   => '40',
						'phone_code' => '386',
					),
					50 => array(
						'country_id' => 212,
						'id'         => 51,
						'name'       => 'KİLİS',
						'plate_no'   => '79',
						'phone_code' => '348',
					),
					51 => array(
						'country_id' => 212,
						'id'         => 52,
						'name'       => 'KOCAELİ',
						'plate_no'   => '41',
						'phone_code' => '262',
					),
					52 => array(
						'country_id' => 212,
						'id'         => 53,
						'name'       => 'KONYA',
						'plate_no'   => '42',
						'phone_code' => '332',
					),
					53 => array(
						'country_id' => 212,
						'id'         => 54,
						'name'       => 'KÜTAHYA',
						'plate_no'   => '43',
						'phone_code' => '274',
					),
					54 => array(
						'country_id' => 212,
						'id'         => 55,
						'name'       => 'MALATYA',
						'plate_no'   => '44',
						'phone_code' => '422',
					),
					55 => array(
						'country_id' => 212,
						'id'         => 56,
						'name'       => 'MANİSA',
						'plate_no'   => '45',
						'phone_code' => '236',
					),
					56 => array(
						'country_id' => 212,
						'id'         => 57,
						'name'       => 'MARDİN',
						'plate_no'   => '47',
						'phone_code' => '482',
					),
					57 => array(
						'country_id' => 212,
						'id'         => 58,
						'name'       => 'MERSİN',
						'plate_no'   => '33',
						'phone_code' => '324',
					),
					58 => array(
						'country_id' => 212,
						'id'         => 59,
						'name'       => 'MUĞLA',
						'plate_no'   => '48',
						'phone_code' => '252',
					),
					59 => array(
						'country_id' => 212,
						'id'         => 60,
						'name'       => 'MUŞ',
						'plate_no'   => '49',
						'phone_code' => '436',
					),
					60 => array(
						'country_id' => 212,
						'id'         => 61,
						'name'       => 'NEVŞEHİR',
						'plate_no'   => '50',
						'phone_code' => '384',
					),
					61 => array(
						'country_id' => 212,
						'id'         => 62,
						'name'       => 'NİĞDE',
						'plate_no'   => '51',
						'phone_code' => '388',
					),
					62 => array(
						'country_id' => 212,
						'id'         => 63,
						'name'       => 'ORDU',
						'plate_no'   => '52',
						'phone_code' => '452',
					),
					63 => array(
						'country_id' => 212,
						'id'         => 64,
						'name'       => 'OSMANİYE',
						'plate_no'   => '80',
						'phone_code' => '328',
					),
					64 => array(
						'country_id' => 212,
						'id'         => 65,
						'name'       => 'RİZE',
						'plate_no'   => '53',
						'phone_code' => '464',
					),
					65 => array(
						'country_id' => 212,
						'id'         => 66,
						'name'       => 'SAKARYA',
						'plate_no'   => '54',
						'phone_code' => '264',
					),
					66 => array(
						'country_id' => 212,
						'id'         => 67,
						'name'       => 'SAMSUN',
						'plate_no'   => '55',
						'phone_code' => '362',
					),
					67 => array(
						'country_id' => 212,
						'id'         => 68,
						'name'       => 'SİİRT',
						'plate_no'   => '56',
						'phone_code' => '484',
					),
					68 => array(
						'country_id' => 212,
						'id'         => 69,
						'name'       => 'SİNOP',
						'plate_no'   => '57',
						'phone_code' => '368',
					),
					69 => array(
						'country_id' => 212,
						'id'         => 70,
						'name'       => 'SİVAS',
						'plate_no'   => '58',
						'phone_code' => '346',
					),
					70 => array(
						'country_id' => 212,
						'id'         => 71,
						'name'       => 'ŞANLIURFA',
						'plate_no'   => '63',
						'phone_code' => '414',
					),
					71 => array(
						'country_id' => 212,
						'id'         => 72,
						'name'       => 'ŞIRNAK',
						'plate_no'   => '73',
						'phone_code' => '486',
					),
					72 => array(
						'country_id' => 212,
						'id'         => 73,
						'name'       => 'TEKİRDAĞ',
						'plate_no'   => '59',
						'phone_code' => '282',
					),
					73 => array(
						'country_id' => 212,
						'id'         => 74,
						'name'       => 'TOKAT',
						'plate_no'   => '60',
						'phone_code' => '356',
					),
					74 => array(
						'country_id' => 212,
						'id'         => 75,
						'name'       => 'TRABZON',
						'plate_no'   => '61',
						'phone_code' => '462',
					),
					75 => array(
						'country_id' => 212,
						'id'         => 76,
						'name'       => 'TUNCELİ',
						'plate_no'   => '62',
						'phone_code' => '428',
					),
					76 => array(
						'country_id' => 212,
						'id'         => 77,
						'name'       => 'UŞAK',
						'plate_no'   => '64',
						'phone_code' => '276',
					),
					77 => array(
						'country_id' => 212,
						'id'         => 78,
						'name'       => 'VAN',
						'plate_no'   => '65',
						'phone_code' => '432',
					),
					78 => array(
						'country_id' => 212,
						'id'         => 79,
						'name'       => 'YALOVA',
						'plate_no'   => '77',
						'phone_code' => '226',
					),
					79 => array(
						'country_id' => 212,
						'id'         => 80,
						'name'       => 'YOZGAT',
						'plate_no'   => '66',
						'phone_code' => '354',
					),
					80 => array(
						'country_id' => 212,
						'id'         => 81,
						'name'       => 'ZONGULDAK',
						'plate_no'   => '67',
						'phone_code' => '372',
					),
				));
			}
	}