<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
	{
		public function run()
			{
				\DB::table('countries')->delete();
				\DB::table('countries')->insert(array(
					0   => array(
						'id'           => 1,
						'name'         => 'Afghanistan',
						'short_name'   => 'AF',
						'short_name_3' => 'AFG',
						'code'         => '93',
					),
					1   => array(
						'id'           => 2,
						'name'         => 'Albania',
						'short_name'   => 'AL',
						'short_name_3' => 'ALB',
						'code'         => '355',
					),
					2   => array(
						'id'           => 3,
						'name'         => 'Algeria',
						'short_name'   => 'DZ',
						'short_name_3' => 'DZA',
						'code'         => '213',
					),
					3   => array(
						'id'           => 4,
						'name'         => 'American Samoa',
						'short_name'   => 'AS',
						'short_name_3' => 'ASM',
						'code'         => '684',
					),
					4   => array(
						'id'           => 5,
						'name'         => 'Andorra',
						'short_name'   => 'AD',
						'short_name_3' => 'AND',
						'code'         => '376',
					),
					5   => array(
						'id'           => 6,
						'name'         => 'Angola',
						'short_name'   => 'AO',
						'short_name_3' => 'AGO',
						'code'         => '244',
					),
					6   => array(
						'id'           => 7,
						'name'         => 'Anguilla',
						'short_name'   => 'AI',
						'short_name_3' => 'AIA',
						'code'         => '264',
					),
					7   => array(
						'id'           => 8,
						'name'         => 'Antarctica',
						'short_name'   => 'AQ',
						'short_name_3' => 'ATA',
						'code'         => '672',
					),
					8   => array(
						'id'           => 9,
						'name'         => 'Antigua and Barbuda',
						'short_name'   => 'AG',
						'short_name_3' => 'ATG',
						'code'         => '268',
					),
					9   => array(
						'id'           => 10,
						'name'         => 'Argentina',
						'short_name'   => 'AR',
						'short_name_3' => 'ARG',
						'code'         => '54',
					),
					10  => array(
						'id'           => 11,
						'name'         => 'Armenia',
						'short_name'   => 'AM',
						'short_name_3' => 'ARM',
						'code'         => '374',
					),
					11  => array(
						'id'           => 12,
						'name'         => 'Aruba',
						'short_name'   => 'AW',
						'short_name_3' => 'ABW',
						'code'         => '297',
					),
					12  => array(
						'id'           => 13,
						'name'         => 'Australia',
						'short_name'   => 'AU',
						'short_name_3' => 'AUS',
						'code'         => '61',
					),
					13  => array(
						'id'           => 14,
						'name'         => 'Austria',
						'short_name'   => 'AT',
						'short_name_3' => 'AUT',
						'code'         => '43',
					),
					14  => array(
						'id'           => 15,
						'name'         => 'Azerbaijan',
						'short_name'   => 'AZ',
						'short_name_3' => 'AZE',
						'code'         => '994',
					),
					15  => array(
						'id'           => 16,
						'name'         => 'Bahamas',
						'short_name'   => 'BS',
						'short_name_3' => 'BHS',
						'code'         => '242',
					),
					16  => array(
						'id'           => 17,
						'name'         => 'Bahrain',
						'short_name'   => 'BH',
						'short_name_3' => 'BHR',
						'code'         => '973',
					),
					17  => array(
						'id'           => 18,
						'name'         => 'Bangladesh',
						'short_name'   => 'BD',
						'short_name_3' => 'BGD',
						'code'         => '880',
					),
					18  => array(
						'id'           => 19,
						'name'         => 'Barbados',
						'short_name'   => 'BB',
						'short_name_3' => 'BRB',
						'code'         => '246',
					),
					19  => array(
						'id'           => 20,
						'name'         => 'Belarus',
						'short_name'   => 'BY',
						'short_name_3' => 'BLR',
						'code'         => '375',
					),
					20  => array(
						'id'           => 21,
						'name'         => 'Belgium',
						'short_name'   => 'BE',
						'short_name_3' => 'BEL',
						'code'         => '32',
					),
					21  => array(
						'id'           => 22,
						'name'         => 'Belize',
						'short_name'   => 'BZ',
						'short_name_3' => 'BLZ',
						'code'         => '501',
					),
					22  => array(
						'id'           => 23,
						'name'         => 'Benin',
						'short_name'   => 'BJ',
						'short_name_3' => 'BEN',
						'code'         => '229',
					),
					23  => array(
						'id'           => 24,
						'name'         => 'Bermuda',
						'short_name'   => 'BM',
						'short_name_3' => 'BMU',
						'code'         => '441',
					),
					24  => array(
						'id'           => 25,
						'name'         => 'Bhutan',
						'short_name'   => 'BT',
						'short_name_3' => 'BTN',
						'code'         => '975',
					),
					25  => array(
						'id'           => 26,
						'name'         => 'Bolivia',
						'short_name'   => 'BO',
						'short_name_3' => 'BOL',
						'code'         => '591',
					),
					26  => array(
						'id'           => 27,
						'name'         => 'Bosnia and Herzegovina',
						'short_name'   => 'BA',
						'short_name_3' => 'BIH',
						'code'         => '387',
					),
					27  => array(
						'id'           => 28,
						'name'         => 'Botswana',
						'short_name'   => 'BW',
						'short_name_3' => 'BWA',
						'code'         => '267',
					),
					28  => array(
						'id'           => 29,
						'name'         => 'Brazil',
						'short_name'   => 'BR',
						'short_name_3' => 'BRA',
						'code'         => '55',
					),
					29  => array(
						'id'           => 30,
						'name'         => 'British Virgin Islands',
						'short_name'   => 'VG',
						'short_name_3' => 'VGB',
						'code'         => '284',
					),
					30  => array(
						'id'           => 31,
						'name'         => 'Brunei',
						'short_name'   => 'BN',
						'short_name_3' => 'BRN',
						'code'         => '673',
					),
					31  => array(
						'id'           => 32,
						'name'         => 'Bulgaria',
						'short_name'   => 'BG',
						'short_name_3' => 'BGR',
						'code'         => '359',
					),
					32  => array(
						'id'           => 33,
						'name'         => 'Burkina Faso',
						'short_name'   => 'BF',
						'short_name_3' => 'BFA',
						'code'         => '226',
					),
					33  => array(
						'id'           => 34,
						'name'         => 'Burundi',
						'short_name'   => 'BI',
						'short_name_3' => 'BDI',
						'code'         => '257',
					),
					34  => array(
						'id'           => 35,
						'name'         => 'Cambodia',
						'short_name'   => 'KH',
						'short_name_3' => 'KHM',
						'code'         => '855',
					),
					35  => array(
						'id'           => 36,
						'name'         => 'Cameroon',
						'short_name'   => 'CM',
						'short_name_3' => 'CMR',
						'code'         => '237',
					),
					36  => array(
						'id'           => 37,
						'name'         => 'Canada',
						'short_name'   => 'CA',
						'short_name_3' => 'CAN',
						'code'         => '1',
					),
					37  => array(
						'id'           => 38,
						'name'         => 'Cape Verde',
						'short_name'   => 'CV',
						'short_name_3' => 'CPV',
						'code'         => '238',
					),
					38  => array(
						'id'           => 39,
						'name'         => 'Cayman Islands',
						'short_name'   => 'KY',
						'short_name_3' => 'CYM',
						'code'         => '345',
					),
					39  => array(
						'id'           => 40,
						'name'         => 'Central African Republic',
						'short_name'   => 'CF',
						'short_name_3' => 'CAF',
						'code'         => '236',
					),
					40  => array(
						'id'           => 41,
						'name'         => 'Chad',
						'short_name'   => 'TD',
						'short_name_3' => 'TCD',
						'code'         => '235',
					),
					41  => array(
						'id'           => 42,
						'name'         => 'Chile',
						'short_name'   => 'CL',
						'short_name_3' => 'CHL',
						'code'         => '56',
					),
					42  => array(
						'id'           => 43,
						'name'         => 'China',
						'short_name'   => 'CN',
						'short_name_3' => 'CHN',
						'code'         => '86',
					),
					43  => array(
						'id'           => 44,
						'name'         => 'Christmas Island',
						'short_name'   => 'CX',
						'short_name_3' => 'CXR',
						'code'         => '61',
					),
					44  => array(
						'id'           => 45,
						'name'         => 'Cocos [Keeling] Islands',
						'short_name'   => 'CC',
						'short_name_3' => 'CCK',
						'code'         => '61',
					),
					45  => array(
						'id'           => 46,
						'name'         => 'Colombia',
						'short_name'   => 'CO',
						'short_name_3' => 'COL',
						'code'         => '57',
					),
					46  => array(
						'id'           => 47,
						'name'         => 'Comoros',
						'short_name'   => 'KM',
						'short_name_3' => 'COM',
						'code'         => '269',
					),
					47  => array(
						'id'           => 48,
						'name'         => 'Congo [DRC]',
						'short_name'   => 'CD',
						'short_name_3' => 'COD',
						'code'         => '242',
					),
					48  => array(
						'id'           => 49,
						'name'         => 'Congo [Republic]',
						'short_name'   => 'CG',
						'short_name_3' => 'COG',
						'code'         => '682',
					),
					49  => array(
						'id'           => 50,
						'name'         => 'Cook Islands',
						'short_name'   => 'CK',
						'short_name_3' => 'COK',
						'code'         => '506',
					),
					50  => array(
						'id'           => 51,
						'name'         => 'Costa Rica',
						'short_name'   => 'CR',
						'short_name_3' => 'CRI',
						'code'         => '385',
					),
					51  => array(
						'id'           => 52,
						'name'         => 'Croatia',
						'short_name'   => 'HR',
						'short_name_3' => 'HRV',
						'code'         => '53',
					),
					52  => array(
						'id'           => 53,
						'name'         => 'Cuba',
						'short_name'   => 'CU',
						'short_name_3' => 'CUB',
						'code'         => '599',
					),
					53  => array(
						'id'           => 54,
						'name'         => 'Cyprus',
						'short_name'   => 'CY',
						'short_name_3' => 'CYP',
						'code'         => '357',
					),
					54  => array(
						'id'           => 55,
						'name'         => 'Czech Republic',
						'short_name'   => 'CZ',
						'short_name_3' => 'CZE',
						'code'         => '420',
					),
					55  => array(
						'id'           => 56,
						'name'         => 'Denmark',
						'short_name'   => 'DK',
						'short_name_3' => 'DNK',
						'code'         => '45',
					),
					56  => array(
						'id'           => 57,
						'name'         => 'Djibouti',
						'short_name'   => 'DJ',
						'short_name_3' => 'DJI',
						'code'         => '253',
					),
					57  => array(
						'id'           => 58,
						'name'         => 'Dominica',
						'short_name'   => 'DM',
						'short_name_3' => 'DMA',
						'code'         => '767',
					),
					58  => array(
						'id'           => 59,
						'name'         => 'Dominican Republic',
						'short_name'   => 'DO',
						'short_name_3' => 'DOM',
						'code'         => '809',
					),
					59  => array(
						'id'           => 60,
						'name'         => 'East Timor',
						'short_name'   => 'TL',
						'short_name_3' => 'TLS',
						'code'         => '56',
					),
					60  => array(
						'id'           => 61,
						'name'         => 'Ecuador',
						'short_name'   => 'EC',
						'short_name_3' => 'ECU',
						'code'         => '593',
					),
					61  => array(
						'id'           => 62,
						'name'         => 'Egypt',
						'short_name'   => 'EG',
						'short_name_3' => 'EGY',
						'code'         => '20',
					),
					62  => array(
						'id'           => 63,
						'name'         => 'El Salvador',
						'short_name'   => 'SV',
						'short_name_3' => 'SLV',
						'code'         => '503',
					),
					63  => array(
						'id'           => 64,
						'name'         => 'Equatorial Guinea',
						'short_name'   => 'GQ',
						'short_name_3' => 'GNQ',
						'code'         => '240',
					),
					64  => array(
						'id'           => 65,
						'name'         => 'Eritrea',
						'short_name'   => 'ER',
						'short_name_3' => 'ERI',
						'code'         => '291',
					),
					65  => array(
						'id'           => 66,
						'name'         => 'Estonia',
						'short_name'   => 'EE',
						'short_name_3' => 'EST',
						'code'         => '372',
					),
					66  => array(
						'id'           => 67,
						'name'         => 'Ethiopia',
						'short_name'   => 'ET',
						'short_name_3' => 'ETH',
						'code'         => '251',
					),
					67  => array(
						'id'           => 68,
						'name'         => 'Falkland Islands',
						'short_name'   => 'FK',
						'short_name_3' => 'FLK',
						'code'         => '500',
					),
					68  => array(
						'id'           => 69,
						'name'         => 'Faroe Islands',
						'short_name'   => 'FO',
						'short_name_3' => 'FRO',
						'code'         => '298',
					),
					69  => array(
						'id'           => 70,
						'name'         => 'Fiji',
						'short_name'   => 'FJ',
						'short_name_3' => 'FJI',
						'code'         => '679',
					),
					70  => array(
						'id'           => 71,
						'name'         => 'Finland',
						'short_name'   => 'FI',
						'short_name_3' => 'FIN',
						'code'         => '358',
					),
					71  => array(
						'id'           => 72,
						'name'         => 'France',
						'short_name'   => 'FR',
						'short_name_3' => 'FRA',
						'code'         => '33',
					),
					72  => array(
						'id'           => 73,
						'name'         => 'French Guiana',
						'short_name'   => 'GF',
						'short_name_3' => 'GUF',
						'code'         => '596',
					),
					73  => array(
						'id'           => 74,
						'name'         => 'French Polynesia',
						'short_name'   => 'PF',
						'short_name_3' => 'PYF',
						'code'         => '594',
					),
					74  => array(
						'id'           => 75,
						'name'         => 'French Southern Territories',
						'short_name'   => 'TF',
						'short_name_3' => 'ATF',
						'code'         => '689',
					),
					75  => array(
						'id'           => 76,
						'name'         => 'Gabon',
						'short_name'   => 'GA',
						'short_name_3' => 'GAB',
						'code'         => '241',
					),
					76  => array(
						'id'           => 77,
						'name'         => 'Gambia',
						'short_name'   => 'GM',
						'short_name_3' => 'GMB',
						'code'         => '220',
					),
					77  => array(
						'id'           => 78,
						'name'         => 'Georgia',
						'short_name'   => 'GE',
						'short_name_3' => 'GEO',
						'code'         => '995',
					),
					78  => array(
						'id'           => 79,
						'name'         => 'Germany',
						'short_name'   => 'DE',
						'short_name_3' => 'DEU',
						'code'         => '49',
					),
					79  => array(
						'id'           => 80,
						'name'         => 'Ghana',
						'short_name'   => 'GH',
						'short_name_3' => 'GHA',
						'code'         => '233',
					),
					80  => array(
						'id'           => 81,
						'name'         => 'Gibraltar',
						'short_name'   => 'GI',
						'short_name_3' => 'GIB',
						'code'         => '350',
					),
					81  => array(
						'id'           => 82,
						'name'         => 'Greece',
						'short_name'   => 'GR',
						'short_name_3' => 'GRC',
						'code'         => '30',
					),
					82  => array(
						'id'           => 83,
						'name'         => 'Greenland',
						'short_name'   => 'GL',
						'short_name_3' => 'GRL',
						'code'         => '299',
					),
					83  => array(
						'id'           => 84,
						'name'         => 'Grenada',
						'short_name'   => 'GD',
						'short_name_3' => 'GRD',
						'code'         => '473',
					),
					84  => array(
						'id'           => 85,
						'name'         => 'Guadeloupe',
						'short_name'   => 'GP',
						'short_name_3' => 'GLP',
						'code'         => '590',
					),
					85  => array(
						'id'           => 86,
						'name'         => 'Guam',
						'short_name'   => 'GU',
						'short_name_3' => 'GUM',
						'code'         => '671',
					),
					86  => array(
						'id'           => 87,
						'name'         => 'Guatemala',
						'short_name'   => 'GT',
						'short_name_3' => 'GTM',
						'code'         => '502',
					),
					87  => array(
						'id'           => 88,
						'name'         => 'Guinea',
						'short_name'   => 'GN',
						'short_name_3' => 'GIN',
						'code'         => '594',
					),
					88  => array(
						'id'           => 89,
						'name'         => 'Guinea-Bissau',
						'short_name'   => 'GW',
						'short_name_3' => 'GNB',
						'code'         => '245',
					),
					89  => array(
						'id'           => 90,
						'name'         => 'Guyana',
						'short_name'   => 'GY',
						'short_name_3' => 'GUY',
						'code'         => '592',
					),
					90  => array(
						'id'           => 91,
						'name'         => 'Haiti',
						'short_name'   => 'HT',
						'short_name_3' => 'HTI',
						'code'         => '509',
					),
					91  => array(
						'id'           => 92,
						'name'         => 'Honduras',
						'short_name'   => 'HN',
						'short_name_3' => 'HND',
						'code'         => '504',
					),
					92  => array(
						'id'           => 93,
						'name'         => 'Hong Kong',
						'short_name'   => 'HK',
						'short_name_3' => 'HKG',
						'code'         => '852',
					),
					93  => array(
						'id'           => 94,
						'name'         => 'Hungary',
						'short_name'   => 'HU',
						'short_name_3' => 'HUN',
						'code'         => '36',
					),
					94  => array(
						'id'           => 95,
						'name'         => 'Iceland',
						'short_name'   => 'IS',
						'short_name_3' => 'ISL',
						'code'         => '354',
					),
					95  => array(
						'id'           => 96,
						'name'         => 'India',
						'short_name'   => 'IN',
						'short_name_3' => 'IND',
						'code'         => '91',
					),
					96  => array(
						'id'           => 97,
						'name'         => 'Indonesia',
						'short_name'   => 'ID',
						'short_name_3' => 'IDN',
						'code'         => '62',
					),
					97  => array(
						'id'           => 98,
						'name'         => 'Iran',
						'short_name'   => 'IR',
						'short_name_3' => 'IRN',
						'code'         => '98',
					),
					98  => array(
						'id'           => 99,
						'name'         => 'Iraq',
						'short_name'   => 'IQ',
						'short_name_3' => 'IRQ',
						'code'         => '964',
					),
					99  => array(
						'id'           => 100,
						'name'         => 'Ireland',
						'short_name'   => 'IE',
						'short_name_3' => 'IRL',
						'code'         => '353',
					),
					100 => array(
						'id'           => 101,
						'name'         => 'Isle of Man',
						'short_name'   => 'IM',
						'short_name_3' => 'IMN',
						'code'         => '44',
					),
					101 => array(
						'id'           => 102,
						'name'         => 'Israel',
						'short_name'   => 'IL',
						'short_name_3' => 'ISR',
						'code'         => '972',
					),
					102 => array(
						'id'           => 103,
						'name'         => 'Italy',
						'short_name'   => 'IT',
						'short_name_3' => 'ITA',
						'code'         => '39',
					),
					103 => array(
						'id'           => 104,
						'name'         => 'Ivory Coast',
						'short_name'   => 'CI',
						'short_name_3' => 'CIV',
						'code'         => '225',
					),
					104 => array(
						'id'           => 105,
						'name'         => 'Jamaica',
						'short_name'   => 'JM',
						'short_name_3' => 'JAM',
						'code'         => '876',
					),
					105 => array(
						'id'           => 106,
						'name'         => 'Japan',
						'short_name'   => 'JP',
						'short_name_3' => 'JPN',
						'code'         => '81',
					),
					106 => array(
						'id'           => 107,
						'name'         => 'Jordan',
						'short_name'   => 'JO',
						'short_name_3' => 'JOR',
						'code'         => '962',
					),
					107 => array(
						'id'           => 108,
						'name'         => 'Kazakhstan',
						'short_name'   => 'KZ',
						'short_name_3' => 'KAZ',
						'code'         => '7',
					),
					108 => array(
						'id'           => 109,
						'name'         => 'Kenya',
						'short_name'   => 'KE',
						'short_name_3' => 'KEN',
						'code'         => '254',
					),
					109 => array(
						'id'           => 110,
						'name'         => 'Kiribati',
						'short_name'   => 'KI',
						'short_name_3' => 'KIR',
						'code'         => '686',
					),
					110 => array(
						'id'           => 111,
						'name'         => 'Kosovo',
						'short_name'   => 'XK',
						'short_name_3' => 'XKX',
						'code'         => '381',
					),
					111 => array(
						'id'           => 112,
						'name'         => 'Kuwait',
						'short_name'   => 'KW',
						'short_name_3' => 'KWT',
						'code'         => '965',
					),
					112 => array(
						'id'           => 113,
						'name'         => 'Kyrgyzstan',
						'short_name'   => 'KG',
						'short_name_3' => 'KGZ',
						'code'         => '996',
					),
					113 => array(
						'id'           => 114,
						'name'         => 'Laos',
						'short_name'   => 'LA',
						'short_name_3' => 'LAO',
						'code'         => '856',
					),
					114 => array(
						'id'           => 115,
						'name'         => 'Latvia',
						'short_name'   => 'LV',
						'short_name_3' => 'LVA',
						'code'         => '371',
					),
					115 => array(
						'id'           => 116,
						'name'         => 'Lebanon',
						'short_name'   => 'LB',
						'short_name_3' => 'LBN',
						'code'         => '961',
					),
					116 => array(
						'id'           => 117,
						'name'         => 'Lesotho',
						'short_name'   => 'LS',
						'short_name_3' => 'LSO',
						'code'         => '266',
					),
					117 => array(
						'id'           => 118,
						'name'         => 'Liberia',
						'short_name'   => 'LR',
						'short_name_3' => 'LBR',
						'code'         => '231',
					),
					118 => array(
						'id'           => 119,
						'name'         => 'Libya',
						'short_name'   => 'LY',
						'short_name_3' => 'LBY',
						'code'         => '218',
					),
					119 => array(
						'id'           => 120,
						'name'         => 'Liechtenstein',
						'short_name'   => 'LI',
						'short_name_3' => 'LIE',
						'code'         => '423',
					),
					120 => array(
						'id'           => 121,
						'name'         => 'Lithuania',
						'short_name'   => 'LT',
						'short_name_3' => 'LTU',
						'code'         => '370',
					),
					121 => array(
						'id'           => 122,
						'name'         => 'Luxembourg',
						'short_name'   => 'LU',
						'short_name_3' => 'LUX',
						'code'         => '352',
					),
					122 => array(
						'id'           => 123,
						'name'         => 'Macau',
						'short_name'   => 'MO',
						'short_name_3' => 'MAC',
						'code'         => '853',
					),
					123 => array(
						'id'           => 124,
						'name'         => 'Macedonia',
						'short_name'   => 'MK',
						'short_name_3' => 'MKD',
						'code'         => '389',
					),
					124 => array(
						'id'           => 125,
						'name'         => 'Madagascar',
						'short_name'   => 'MG',
						'short_name_3' => 'MDG',
						'code'         => '261',
					),
					125 => array(
						'id'           => 126,
						'name'         => 'Malawi',
						'short_name'   => 'MW',
						'short_name_3' => 'MWI',
						'code'         => '265',
					),
					126 => array(
						'id'           => 127,
						'name'         => 'Malaysia',
						'short_name'   => 'MY',
						'short_name_3' => 'MYS',
						'code'         => '60',
					),
					127 => array(
						'id'           => 128,
						'name'         => 'Maldives',
						'short_name'   => 'MV',
						'short_name_3' => 'MDV',
						'code'         => '960',
					),
					128 => array(
						'id'           => 129,
						'name'         => 'Mali',
						'short_name'   => 'ML',
						'short_name_3' => 'MLI',
						'code'         => '223',
					),
					129 => array(
						'id'           => 130,
						'name'         => 'Malta',
						'short_name'   => 'MT',
						'short_name_3' => 'MLT',
						'code'         => '356',
					),
					130 => array(
						'id'           => 131,
						'name'         => 'Marshall Islands',
						'short_name'   => 'MH',
						'short_name_3' => 'MHL',
						'code'         => '692',
					),
					131 => array(
						'id'           => 132,
						'name'         => 'Martinique',
						'short_name'   => 'MQ',
						'short_name_3' => 'MTQ',
						'code'         => '670',
					),
					132 => array(
						'id'           => 133,
						'name'         => 'Mauritania',
						'short_name'   => 'MR',
						'short_name_3' => 'MRT',
						'code'         => '222',
					),
					133 => array(
						'id'           => 134,
						'name'         => 'Mauritius',
						'short_name'   => 'MU',
						'short_name_3' => 'MUS',
						'code'         => '230',
					),
					134 => array(
						'id'           => 135,
						'name'         => 'Mayotte',
						'short_name'   => 'YT',
						'short_name_3' => 'MYT',
						'code'         => '269',
					),
					135 => array(
						'id'           => 136,
						'name'         => 'Mexico',
						'short_name'   => 'MX',
						'short_name_3' => 'MEX',
						'code'         => '52',
					),
					136 => array(
						'id'           => 137,
						'name'         => 'Micronesia',
						'short_name'   => 'FM',
						'short_name_3' => 'FSM',
						'code'         => '691',
					),
					137 => array(
						'id'           => 138,
						'name'         => 'Moldova',
						'short_name'   => 'MD',
						'short_name_3' => 'MDA',
						'code'         => '373',
					),
					138 => array(
						'id'           => 139,
						'name'         => 'Monaco',
						'short_name'   => 'MC',
						'short_name_3' => 'MCO',
						'code'         => '377',
					),
					139 => array(
						'id'           => 140,
						'name'         => 'Mongolia',
						'short_name'   => 'MN',
						'short_name_3' => 'MNG',
						'code'         => '976',
					),
					140 => array(
						'id'           => 141,
						'name'         => 'Montserrat',
						'short_name'   => 'MS',
						'short_name_3' => 'MSR',
						'code'         => '664',
					),
					141 => array(
						'id'           => 142,
						'name'         => 'Morocco',
						'short_name'   => 'MA',
						'short_name_3' => 'MAR',
						'code'         => '212',
					),
					142 => array(
						'id'           => 143,
						'name'         => 'Mozambique',
						'short_name'   => 'MZ',
						'short_name_3' => 'MOZ',
						'code'         => '258',
					),
					143 => array(
						'id'           => 144,
						'name'         => 'Myanmar [Burma]',
						'short_name'   => 'MM',
						'short_name_3' => 'MMR',
						'code'         => '95',
					),
					144 => array(
						'id'           => 145,
						'name'         => 'Namibia',
						'short_name'   => 'NA',
						'short_name_3' => 'NAM',
						'code'         => '264',
					),
					145 => array(
						'id'           => 146,
						'name'         => 'Nauru',
						'short_name'   => 'NR',
						'short_name_3' => 'NRU',
						'code'         => '674',
					),
					146 => array(
						'id'           => 147,
						'name'         => 'Nepal',
						'short_name'   => 'NP',
						'short_name_3' => 'NPL',
						'code'         => '977',
					),
					147 => array(
						'id'           => 148,
						'name'         => 'Netherlands',
						'short_name'   => 'NL',
						'short_name_3' => 'NLD',
						'code'         => '31',
					),
					148 => array(
						'id'           => 149,
						'name'         => 'Netherlands Antilles',
						'short_name'   => 'AN',
						'short_name_3' => 'ANT',
						'code'         => '599',
					),
					149 => array(
						'id'           => 150,
						'name'         => 'New Caledonia',
						'short_name'   => 'NC',
						'short_name_3' => 'NCL',
						'code'         => '687',
					),
					150 => array(
						'id'           => 151,
						'name'         => 'New Zealand',
						'short_name'   => 'NZ',
						'short_name_3' => 'NZL',
						'code'         => '64',
					),
					151 => array(
						'id'           => 152,
						'name'         => 'Nicaragua',
						'short_name'   => 'NI',
						'short_name_3' => 'NIC',
						'code'         => '505',
					),
					152 => array(
						'id'           => 153,
						'name'         => 'Niger',
						'short_name'   => 'NE',
						'short_name_3' => 'NER',
						'code'         => '227',
					),
					153 => array(
						'id'           => 154,
						'name'         => 'Nigeria',
						'short_name'   => 'NG',
						'short_name_3' => 'NGA',
						'code'         => '234',
					),
					154 => array(
						'id'           => 155,
						'name'         => 'Niue',
						'short_name'   => 'NU',
						'short_name_3' => 'NIU',
						'code'         => '683',
					),
					155 => array(
						'id'           => 156,
						'name'         => 'Norfolk Island',
						'short_name'   => 'NF',
						'short_name_3' => 'NFK',
						'code'         => '672',
					),
					156 => array(
						'id'           => 157,
						'name'         => 'North Korea',
						'short_name'   => 'KP',
						'short_name_3' => 'PRK',
						'code'         => '850',
					),
					157 => array(
						'id'           => 158,
						'name'         => 'Norway',
						'short_name'   => 'NO',
						'short_name_3' => 'NOR',
						'code'         => '47',
					),
					158 => array(
						'id'           => 159,
						'name'         => 'Oman',
						'short_name'   => 'OM',
						'short_name_3' => 'OMN',
						'code'         => '968',
					),
					159 => array(
						'id'           => 160,
						'name'         => 'Pakistan',
						'short_name'   => 'PK',
						'short_name_3' => 'PAK',
						'code'         => '92',
					),
					160 => array(
						'id'           => 161,
						'name'         => 'Palau',
						'short_name'   => 'PW',
						'short_name_3' => 'PLW',
						'code'         => '680',
					),
					161 => array(
						'id'           => 162,
						'name'         => 'Panama',
						'short_name'   => 'PA',
						'short_name_3' => 'PAN',
						'code'         => '507',
					),
					162 => array(
						'id'           => 163,
						'name'         => 'Papua New Guinea',
						'short_name'   => 'PG',
						'short_name_3' => 'PNG',
						'code'         => '675',
					),
					163 => array(
						'id'           => 164,
						'name'         => 'Paraguay',
						'short_name'   => 'PY',
						'short_name_3' => 'PRY',
						'code'         => '595',
					),
					164 => array(
						'id'           => 165,
						'name'         => 'Peru',
						'short_name'   => 'PE',
						'short_name_3' => 'PER',
						'code'         => '51',
					),
					165 => array(
						'id'           => 166,
						'name'         => 'Philippines',
						'short_name'   => 'PH',
						'short_name_3' => 'PHL',
						'code'         => '63',
					),
					166 => array(
						'id'           => 167,
						'name'         => 'Pitcairn Islands',
						'short_name'   => 'PN',
						'short_name_3' => 'PCN',
						'code'         => '48',
					),
					167 => array(
						'id'           => 168,
						'name'         => 'Poland',
						'short_name'   => 'PL',
						'short_name_3' => 'POL',
						'code'         => '351',
					),
					168 => array(
						'id'           => 169,
						'name'         => 'Portugal',
						'short_name'   => 'PT',
						'short_name_3' => 'PRT',
						'code'         => '239',
					),
					169 => array(
						'id'           => 170,
						'name'         => 'Puerto Rico',
						'short_name'   => 'PR',
						'short_name_3' => 'PRI',
						'code'         => '787',
					),
					170 => array(
						'id'           => 171,
						'name'         => 'Qatar',
						'short_name'   => 'QA',
						'short_name_3' => 'QAT',
						'code'         => '974',
					),
					171 => array(
						'id'           => 172,
						'name'         => 'R',
						'short_name'   => 'RE',
						'short_name_3' => 'REU',
						'code'         => '262',
					),
					172 => array(
						'id'           => 173,
						'name'         => 'Romania',
						'short_name'   => 'RO',
						'short_name_3' => 'ROU',
						'code'         => '40',
					),
					173 => array(
						'id'           => 174,
						'name'         => 'Russia',
						'short_name'   => 'RU',
						'short_name_3' => 'RUS',
						'code'         => '7',
					),
					174 => array(
						'id'           => 175,
						'name'         => 'Rwanda',
						'short_name'   => 'RW',
						'short_name_3' => 'RWA',
						'code'         => '250',
					),
					175 => array(
						'id'           => 176,
						'name'         => 'Saint Helena',
						'short_name'   => 'SH',
						'short_name_3' => 'SHN',
						'code'         => '290',
					),
					176 => array(
						'id'           => 177,
						'name'         => 'Saint Kitts and Nevis',
						'short_name'   => 'KN',
						'short_name_3' => 'KNA',
						'code'         => '869',
					),
					177 => array(
						'id'           => 178,
						'name'         => 'Saint Lucia',
						'short_name'   => 'LC',
						'short_name_3' => 'LCA',
						'code'         => '758',
					),
					178 => array(
						'id'           => 179,
						'name'         => 'Saint Pierre and Miquelon',
						'short_name'   => 'PM',
						'short_name_3' => 'SPM',
						'code'         => '508',
					),
					179 => array(
						'id'           => 180,
						'name'         => 'Saint Vincent and the Grenadines',
						'short_name'   => 'VC',
						'short_name_3' => 'VCT',
						'code'         => '784',
					),
					180 => array(
						'id'           => 181,
						'name'         => 'San Marino',
						'short_name'   => 'SM',
						'short_name_3' => 'SMR',
						'code'         => '378',
					),
					181 => array(
						'id'           => 182,
						'name'         => 'Sao Tome and Principe',
						'short_name'   => 'ST',
						'short_name_3' => 'STP',
						'code'         => '239',
					),
					182 => array(
						'id'           => 183,
						'name'         => 'Saudi Arabia',
						'short_name'   => 'SA',
						'short_name_3' => 'SAU',
						'code'         => '966',
					),
					183 => array(
						'id'           => 184,
						'name'         => 'Senegal',
						'short_name'   => 'SN',
						'short_name_3' => 'SEN',
						'code'         => '221',
					),
					184 => array(
						'id'           => 185,
						'name'         => 'Serbia',
						'short_name'   => 'RS',
						'short_name_3' => 'SRB',
						'code'         => '381',
					),
					185 => array(
						'id'           => 186,
						'name'         => 'Seychelles',
						'short_name'   => 'SC',
						'short_name_3' => 'SYC',
						'code'         => '248',
					),
					186 => array(
						'id'           => 187,
						'name'         => 'Sierra Leone',
						'short_name'   => 'SL',
						'short_name_3' => 'SLE',
						'code'         => '232',
					),
					187 => array(
						'id'           => 188,
						'name'         => 'Singapore',
						'short_name'   => 'SG',
						'short_name_3' => 'SGP',
						'code'         => '65',
					),
					188 => array(
						'id'           => 189,
						'name'         => 'Slovakia',
						'short_name'   => 'SK',
						'short_name_3' => 'SVK',
						'code'         => '421',
					),
					189 => array(
						'id'           => 190,
						'name'         => 'Slovenia',
						'short_name'   => 'SI',
						'short_name_3' => 'SVN',
						'code'         => '386',
					),
					190 => array(
						'id'           => 191,
						'name'         => 'Solomon Islands',
						'short_name'   => 'SB',
						'short_name_3' => 'SLB',
						'code'         => '677',
					),
					191 => array(
						'id'           => 192,
						'name'         => 'Somalia',
						'short_name'   => 'SO',
						'short_name_3' => 'SOM',
						'code'         => '252',
					),
					192 => array(
						'id'           => 193,
						'name'         => 'South Africa',
						'short_name'   => 'ZA',
						'short_name_3' => 'ZAF',
						'code'         => '27',
					),
					193 => array(
						'id'           => 194,
						'name'         => 'South Korea',
						'short_name'   => 'KR',
						'short_name_3' => 'KOR',
						'code'         => '82',
					),
					194 => array(
						'id'           => 195,
						'name'         => 'Spain',
						'short_name'   => 'ES',
						'short_name_3' => 'ESP',
						'code'         => '34',
					),
					195 => array(
						'id'           => 196,
						'name'         => 'Sri Lanka',
						'short_name'   => 'LK',
						'short_name_3' => 'LKA',
						'code'         => '94',
					),
					196 => array(
						'id'           => 197,
						'name'         => 'Sudan',
						'short_name'   => 'SD',
						'short_name_3' => 'SDN',
						'code'         => '249',
					),
					197 => array(
						'id'           => 198,
						'name'         => 'Suriname',
						'short_name'   => 'SR',
						'short_name_3' => 'SUR',
						'code'         => '597',
					),
					198 => array(
						'id'           => 199,
						'name'         => 'Swaziland',
						'short_name'   => 'SZ',
						'short_name_3' => 'SWZ',
						'code'         => '268',
					),
					199 => array(
						'id'           => 200,
						'name'         => 'Sweden',
						'short_name'   => 'SE',
						'short_name_3' => 'SWE',
						'code'         => '46',
					),
					200 => array(
						'id'           => 201,
						'name'         => 'Switzerland',
						'short_name'   => 'CH',
						'short_name_3' => 'CHE',
						'code'         => '41',
					),
					201 => array(
						'id'           => 202,
						'name'         => 'Syria',
						'short_name'   => 'SY',
						'short_name_3' => 'SYR',
						'code'         => '963',
					),
					202 => array(
						'id'           => 203,
						'name'         => 'Taiwan',
						'short_name'   => 'TW',
						'short_name_3' => 'TWN',
						'code'         => '886',
					),
					203 => array(
						'id'           => 204,
						'name'         => 'Tajikistan',
						'short_name'   => 'TJ',
						'short_name_3' => 'TJK',
						'code'         => '992',
					),
					204 => array(
						'id'           => 205,
						'name'         => 'Tanzania',
						'short_name'   => 'TZ',
						'short_name_3' => 'TZA',
						'code'         => '255',
					),
					205 => array(
						'id'           => 206,
						'name'         => 'Thailand',
						'short_name'   => 'TH',
						'short_name_3' => 'THA',
						'code'         => '66',
					),
					206 => array(
						'id'           => 207,
						'name'         => 'Togo',
						'short_name'   => 'TG',
						'short_name_3' => 'TGO',
						'code'         => '228',
					),
					207 => array(
						'id'           => 208,
						'name'         => 'Tokelau',
						'short_name'   => 'TK',
						'short_name_3' => 'TKL',
						'code'         => '690',
					),
					208 => array(
						'id'           => 209,
						'name'         => 'Tonga',
						'short_name'   => 'TO',
						'short_name_3' => 'TON',
						'code'         => '676',
					),
					209 => array(
						'id'           => 210,
						'name'         => 'Trinidad and Tobago',
						'short_name'   => 'TT',
						'short_name_3' => 'TTO',
						'code'         => '868',
					),
					210 => array(
						'id'           => 211,
						'name'         => 'Tunisia',
						'short_name'   => 'TN',
						'short_name_3' => 'TUN',
						'code'         => '216',
					),
					211 => array(
						'id'           => 212,
						'name'         => 'Türkiye',
						'short_name'   => 'TR',
						'short_name_3' => 'TUR',
						'code'         => '90',
					),
					212 => array(
						'id'           => 213,
						'name'         => 'Turkmenistan',
						'short_name'   => 'TM',
						'short_name_3' => 'TKM',
						'code'         => '993',
					),
					213 => array(
						'id'           => 214,
						'name'         => 'Turks and Caicos Islands',
						'short_name'   => 'TC',
						'short_name_3' => 'TCA',
						'code'         => '649',
					),
					214 => array(
						'id'           => 215,
						'name'         => 'Tuvalu',
						'short_name'   => 'TV',
						'short_name_3' => 'TUV',
						'code'         => '688',
					),
					215 => array(
						'id'           => 216,
						'name'         => 'U.S. Virgin Islands',
						'short_name'   => 'VI',
						'short_name_3' => 'VIR',
						'code'         => '340',
					),
					216 => array(
						'id'           => 217,
						'name'         => 'Uganda',
						'short_name'   => 'UG',
						'short_name_3' => 'UGA',
						'code'         => '256',
					),
					217 => array(
						'id'           => 218,
						'name'         => 'Ukraine',
						'short_name'   => 'UA',
						'short_name_3' => 'UKR',
						'code'         => '380',
					),
					218 => array(
						'id'           => 219,
						'name'         => 'United Arab Emirates',
						'short_name'   => 'AE',
						'short_name_3' => 'ARE',
						'code'         => '971',
					),
					219 => array(
						'id'           => 220,
						'name'         => 'United Kingdom',
						'short_name'   => 'GB',
						'short_name_3' => 'GBR',
						'code'         => '44',
					),
					220 => array(
						'id'           => 221,
						'name'         => 'United States',
						'short_name'   => 'US',
						'short_name_3' => 'USA',
						'code'         => '1',
					),
					221 => array(
						'id'           => 222,
						'name'         => 'Uruguay',
						'short_name'   => 'UY',
						'short_name_3' => 'URY',
						'code'         => '598',
					),
					222 => array(
						'id'           => 223,
						'name'         => 'Uzbekistan',
						'short_name'   => 'UZ',
						'short_name_3' => 'UZB',
						'code'         => '998',
					),
					223 => array(
						'id'           => 224,
						'name'         => 'Vanuatu',
						'short_name'   => 'VU',
						'short_name_3' => 'VUT',
						'code'         => '678',
					),
					224 => array(
						'id'           => 225,
						'name'         => 'Vatican City',
						'short_name'   => 'VA',
						'short_name_3' => 'VAT',
						'code'         => '39',
					),
					225 => array(
						'id'           => 226,
						'name'         => 'Venezuela',
						'short_name'   => 'VE',
						'short_name_3' => 'VEN',
						'code'         => '58',
					),
					226 => array(
						'id'           => 227,
						'name'         => 'Vietnam',
						'short_name'   => 'VN',
						'short_name_3' => 'VNM',
						'code'         => '84',
					),
					227 => array(
						'id'           => 228,
						'name'         => 'Wallis and Futuna',
						'short_name'   => 'WF',
						'short_name_3' => 'WLF',
						'code'         => '681',
					),
					228 => array(
						'id'           => 229,
						'name'         => 'Yemen',
						'short_name'   => 'YE',
						'short_name_3' => 'YEM',
						'code'         => '967',
					),
					229 => array(
						'id'           => 230,
						'name'         => 'Zambia',
						'short_name'   => 'ZM',
						'short_name_3' => 'ZMB',
						'code'         => '260',
					),
					230 => array(
						'id'           => 231,
						'name'         => 'Zimbabwe',
						'short_name'   => 'ZW',
						'short_name_3' => 'ZWE',
						'code'         => '263',
					),
					231 => array(
						'id'           => 232,
						'name'         => 'KKTC',
						'short_name'   => 'CY',
						'short_name_3' => 'CYP',
						'code'         => '90',
					),
				));
			}
	}